# Generated by Django 2.1.7 on 2020-10-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('c1', models.CharField(max_length=20)),
                ('c2', models.CharField(max_length=20)),
                ('c3', models.CharField(max_length=20)),
                ('c4', models.CharField(max_length=20)),
                ('c5', models.CharField(max_length=20)),
                ('c6', models.CharField(max_length=20)),
                ('c7', models.CharField(max_length=20)),
            ],
        ),
    ]
